const getDaysBefore = require('../utils/getDaysBefore');

module.exports = {
    up: async queryInterface => {
        const insert = queryInterface.bulkInsert(
            'cards',
            [
                {
                    id: 1,
                    activity_id: 1,
                    patient_id: 1,
                    insurance_id: 1,
                    visit_id: '134651',
                    bill_id: 1,
                    total_amount: 1502.1,
                    number_of_pendencies: 2,
                    number_of_open_pendencies: 0,
                    number_of_documents: 4,
                    number_of_not_received_documents: 1,
                    number_of_checklist_items: 4,
                    number_of_done_checklist_items: 4,
                    created_at: getDaysBefore(5),
                    updated_at: getDaysBefore(5),
                },
                {
                    id: 2,
                    activity_id: 1,
                    patient_id: 2,
                    insurance_id: 2,
                    visit_id: '1343151',
                    bill_id: 2,
                    total_amount: 500.5,
                    number_of_pendencies: 2,
                    number_of_open_pendencies: 0,
                    number_of_documents: 4,
                    number_of_not_received_documents: 0,
                    number_of_checklist_items: 4,
                    number_of_done_checklist_items: 4,
                    created_at: getDaysBefore(3),
                    updated_at: getDaysBefore(3),
                },
                {
                    id: 3,
                    activity_id: 1,
                    patient_id: 3,
                    insurance_id: 2,
                    visit_id: '1341251',
                    bill_id: 3,
                    total_amount: 299.5,
                    number_of_pendencies: 2,
                    number_of_open_pendencies: 7,
                    number_of_documents: 4,
                    number_of_not_received_documents: 0,
                    number_of_checklist_items: 3,
                    number_of_done_checklist_items: 4,
                    created_at: getDaysBefore(1),
                    updated_at: getDaysBefore(1),
                },
                {
                    id: 4,
                    activity_id: 1,
                    patient_id: 4,
                    insurance_id: 4,
                    visit_id: '1345112',
                    bill_id: 4,
                    total_amount: 299.5,
                    number_of_pendencies: 2,
                    number_of_open_pendencies: 0,
                    number_of_documents: 4,
                    number_of_not_received_documents: 2,
                    number_of_checklist_items: 3,
                    number_of_done_checklist_items: 4,
                    created_at: getDaysBefore(8),
                    updated_at: getDaysBefore(8),
                },
                {
                    id: 5,
                    activity_id: 1,
                    patient_id: 5,
                    insurance_id: 4,
                    visit_id: '13451312312',
                    bill_id: 5,
                    total_amount: 299.5,
                    number_of_pendencies: 2,
                    number_of_open_pendencies: 0,
                    number_of_documents: 4,
                    number_of_not_received_documents: 2,
                    number_of_checklist_items: 4,
                    number_of_done_checklist_items: 4,
                    created_at: getDaysBefore(7),
                    updated_at: getDaysBefore(7),
                },
                {
                    id: 6,
                    activity_id: 1,
                    patient_id: 6,
                    insurance_id: 4,
                    visit_id: '13451312312',
                    bill_id: 6,
                    total_amount: 299.5,
                    number_of_pendencies: 2,
                    number_of_open_pendencies: 1,
                    number_of_documents: 4,
                    number_of_not_received_documents: 0,
                    number_of_checklist_items: 4,
                    number_of_done_checklist_items: 4,
                    created_at: getDaysBefore(9),
                    updated_at: getDaysBefore(9),
                },
                {
                    id: 7,
                    activity_id: 1,
                    patient_id: 7,
                    insurance_id: 4,
                    visit_id: '13451312312',
                    bill_id: 7,
                    total_amount: 299.5,
                    number_of_pendencies: 2,
                    number_of_open_pendencies: 2,
                    number_of_documents: 4,
                    number_of_not_received_documents: 0,
                    number_of_checklist_items: 4,
                    number_of_done_checklist_items: 4,
                    created_at: getDaysBefore(9),
                    updated_at: getDaysBefore(9),
                },
                {
                    id: 8,
                    activity_id: 1,
                    patient_id: 8,
                    insurance_id: 1,
                    visit_id: '13451312312',
                    bill_id: 8,
                    total_amount: 299.5,
                    number_of_pendencies: 2,
                    number_of_open_pendencies: 4,
                    number_of_documents: 4,
                    number_of_not_received_documents: 0,
                    number_of_checklist_items: 4,
                    number_of_done_checklist_items: 4,
                    created_at: getDaysBefore(10),
                    updated_at: getDaysBefore(10),
                },
                {
                    id: 9,
                    activity_id: 1,
                    patient_id: 9,
                    insurance_id: 2,
                    visit_id: '13451312312',
                    bill_id: 9,
                    total_amount: 299.5,
                    number_of_pendencies: 2,
                    number_of_open_pendencies: 0,
                    number_of_documents: 4,
                    number_of_not_received_documents: 0,
                    number_of_checklist_items: 4,
                    number_of_done_checklist_items: 4,
                    created_at: getDaysBefore(11),
                    updated_at: getDaysBefore(11),
                },
            ],
            {}
        );

        await queryInterface.sequelize.query(
            `ALTER SEQUENCE "cards_id_seq" RESTART WITH ${10}`
        );
        return insert;
    },

    down: queryInterface => {
        return queryInterface.bulkDelete('cards', null, {});
    },
};
